name: Epic
description: Issue para organizar um grupo de funcionalidades ou tarefas relacionadas
title: "[EPIC] "
labels: ["Epic"]
projects: ["seu-usuario/seu-projeto"]
body:
  - type: textarea
    id: objetivo
    attributes:
      label: Objetivo da Epic
      description: Descreva o objetivo geral dessa Epic e o que será entregue.
      placeholder: Definir a arquitetura do Data Lake.
  - type: textarea
    id: features
    attributes:
      label: Features relacionadas
      description: Liste as funcionalidades que fazem parte dessa Epic (adicione links para issues existentes ou crie novas).
      placeholder: |
        - [ ] #10 - [Feature] Estrutura de zonas
        - [ ] #11 - [Feature] Ingestão de dados
  - type: markdown
    attributes:
      value: "**Criar novas Features para essa Epic:**"
  - type: textarea
    id: subissues
    attributes:
      label: Criar novas Features para esta Epic
      description: Digite o título das novas Features, uma por linha. Elas serão criadas automaticamente e associadas a essa Epic.
      placeholder: |
        Exemplo:
        - Estrutura de zonas
        - Escolha da ferramenta de ingestão
  - type: input
    id: estimativa
    attributes:
      label: Estimativa geral de esforço (Story Points)
  - type: dropdown
    id: prioridade
    attributes:
      label: Prioridade da Epic
      options:
        - Alta
        - Média
        - Baixa

