name: Feature
description: Template para criação de uma nova funcionalidade do sistema
title: "[Feature] "
labels: ["feature"]
projects: ["seu-usuario/seu-projeto"] # substitua aqui, se desejar vincular a um GitHub Project automaticamente
body:
  - type: textarea
    id: objetivo
    attributes:
      label: 🎯 Objetivo da Feature
      description: Explique o que será entregue com essa funcionalidade.
      placeholder: Criar estrutura de zonas no Data Lake (raw, processed, trusted)
    validations:
      required: true

  - type: textarea
    id: tarefas
    attributes:
      label: ✅ Subtarefas
      description: Liste as etapas necessárias para concluir essa feature.
      placeholder: |
        - [ ] Escrever documentação
        - [ ] Criar diretórios de cada zona
        - [ ] Validar com o time
    validations:
      required: false

  - type: input
    id: estimativa
    attributes:
      label: 📈 Estimativa de esforço (Story Points)
      placeholder: 5
    validations:
      required: false

  - type: dropdown
    id: prioridade
    attributes:
      label: 🔥 Prioridade
      options:
        - Alta
        - Média
        - Baixa
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: ⚙️ Checklist de Entrega
      options:
        - label: Criar branch automaticamente para a feature
        - label: Implementar a funcionalidade
        - label: Testar localmente (se aplicável)
        - label: Criar Pull Request
        - label: Atualizar documentação

