name: Tarefa
description: Template padrão para tarefas executáveis do projeto
title: "[Tarefa] "
labels: ["tarefa"]
body:
  - type: textarea
    id: descricao
    attributes:
      label: Descrição da Tarefa
      description: O que precisa ser feito?
      placeholder: Escrever documentação explicando cada zona do Data Lake.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: Escrever código ou documentação
        - label: Testar localmente (se aplicável)
        - label: Atualizar README ou docs (se necessário)
        - label: Abrir Pull Request (se aplicável)
  - type: input
    id: estimativa
    attributes:
      label: Estimativa de Esforço (Story Points)

