name: Tarefa
description: Template padrão para tarefas executáveis do projeto
title: "[Tarefa] "
labels: ["Task"]
projects: ["seu-usuario/seu-projeto"]
body:
  - type: textarea
    id: descricao
    attributes:
      label: Descrição da Tarefa
      description: O que precisa ser feito?
      placeholder: Exemplo: Escrever documentação explicando cada zona do Data Lake.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: Executar atividade dentro da branch da Feature
        - label: Validar entrega com time (se necessário)
        - label: Atualizar documentação (se aplicável)
  - type: input
    id: estimativa
    attributes:
      label: Estimativa de Esforço (Story Points)

