name: Criar branch automaticamente para Features

on:
  issues:
    types: [opened, edited, labeled]

jobs:
  create-feature-branch:
    if: contains(github.event.issue.labels.*.name, 'feature')
    runs-on: ubuntu-latest

    steps:
      - name: Checar se a checkbox está marcada
        id: check
        run: |
          body="${{ github.event.issue.body }}"
          echo "Corpo da issue:"
          echo "$body"

          # Verifica se o checkbox está marcado
          if echo "$body" | grep -q '\[x\] Criar branch automaticamente para a feature'; then
            echo "create_branch=true" >> $GITHUB_OUTPUT
          else
            echo "create_branch=false" >> $GITHUB_OUTPUT
          fi

      - name: Clonar repositório
        if: steps.check.outputs.create_branch == 'true'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} repo
          cd repo

          issue_number=${{ github.event.issue.number }}
          title="${{ github.event.issue.title }}"
          slug=$(echo "$title" | sed 's/\[Feature\] //' | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g')
          branch_name="feature/${issue_number}-${slug}"

          echo "Criando branch: $branch_name"
          git checkout -b "$branch_name"
          git push origin "$branch_name"

